---
name: "JellyExplorer"
guid: "f1c1b09f-6f1b-4e1c-b9d9-e1f4b4d4f1c1"
version: "1.0.0.0"
targetAbi: "10.8.9.0"
framework: "net7.0"
overview: "A plugin for Jellyfin"
description: >
  This plugin allows users to do ___ directly from the Jellyfin web interface.
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.JellyExplorer.dll"
changelog: >
  Setup a project structure for better organization with Models, Pages, Controllers, etc.
